# Generated by Django 3.2.8 on 2021-12-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_category',
            new_name='post_categoryes',
        ),
    ]
